### ISSUE TITLE
Why use templates/partials/introduction.html?

### ISSUE THREAD

**Issue by wucke13** [janbaudisch/zola-hallo#1]
The way I understand zola, it would make more sense to use the html file created from `content/_index.md` instead of a html file inside of  templates/partials/introduction.html. The current setup undermines basically the whole static site generator principle of using markdown for content. Like, the only content which is meant to be changed is __not__ written in markdown. 

Is there a good reason for this?

**Comment by janbaudisch** [comment]
Fixed in #2.
